#ifndef MATHLIB_H
#define MATHLIB_H

VIP_ENCDOUBLE myfloor(VIP_ENCDOUBLE x);
VIP_ENCDOUBLE myround(VIP_ENCDOUBLE x);
VIP_ENCDOUBLE myfabs(VIP_ENCDOUBLE x);
VIP_ENCDOUBLE mypow(VIP_ENCDOUBLE x, unsigned exp);
VIP_ENCDOUBLE mysqrt(VIP_ENCDOUBLE num);
VIP_ENCDOUBLE mysin(VIP_ENCDOUBLE x);
VIP_ENCDOUBLE mycos(VIP_ENCDOUBLE x);
VIP_ENCDOUBLE myexp(VIP_ENCDOUBLE x);
VIP_ENCDOUBLE mylog(VIP_ENCDOUBLE x);

#endif /* MATHLAB_H */
